version: "3.3"
services:
  sonarqube:
    image: sonarqube:lts
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
    

  db:
    image: postgres:14.1-alpine
    networks:
      - sonarnet
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=Test12345
   

networks:
  sonarnet:
    driver: bridge

