version: '3.7'
services:
 frontend:
  build:
   context : .
   dockerfile : Dockerfile
  container_name : Front
  expose:
   - "4200"
  depends_on:
   - nginx_proxy
  restart : always

 nginx_proxy:
  build:
    context : ./nginx
    dockerfile : Dockerfile
  container_name: nginx_Front
  volumes:
   - ./:/var/www
  ports:
   - "4001:80"
  restart : always
