version: '3.7'
services:
 partie_frontend:
  build:
   context : .
   dockerfile : Dockerfile
  container_name : front
  volumes:
   - ./:/var/www
  expose:
   - "4200"
  depends_on:
   - nginx_proxy
  networks:
      - net
  restart : always

 nginx_proxy:
  build:
    context : .
    dockerfile : Dockerfile
  container_name: nginx_front
  volumes:
   - ./:/var/www
  ports:
   - "4002:80"
  networks:
    - net
  restart : always
networks:
  net:
    driver: bridge