version: '3.7'
services:
 frontend:
  build:
   context : ./DevOpsFront/
   dockerfile : Dockerfile
  container_name : Front
  expose:
   - "5001"
  depends_on:
   - nginx_proxy
  restart : always

 nginx_proxy:
  build:
    context : ./nginx/front
    dockerfile : Dockerfile
  container_name: nginx_Front
  volumes:
   - ./:/var/www
  ports:
   - "4000:80"
  restart : always
