version: "3.7"
services:
  elasticsearch:
    container_name: elasticsearch_container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    environment:
      #- xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - es-net
    ports:
      - 9200:9200
  kibana:
    container_name: kibana_container
    image: docker.elastic.co/kibana/kibana:7.5.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch_container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
networks:
  es-net:
    driver: bridge