version: "3.7"
services:
  db:
    image: postgres:14.1-alpine
    environment:
        - POSTGRES_USER=sonar

        - POSTGRES_PASSWORD=sonar

        - POSTGRES_DB=sonar
    ports: 
        - '5432:5432'
    volumes:
        - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
        - sonarqube-net
  sonarqube:

      image: sonarqube:8.9-community

      depends_on:

        - db

      environment:

        - sonar.jdbc.username=sonar

        - sonar.jdbc.url=jdbc:postgresql://db/sonar

        - sonar.jdbc.password=sonar

      ports:

        - 9000:9000

      volumes:

        - sonar_conf:/opt/sonarqube/conf

        - sonar_data:/opt/sonarqube/data

        - sonar_extensions:/opt/sonarqube/extensions

        - sonar_plugins:/opt/sonarqube/lib/bundled-plugins

      networks:

      - sonarqube-net

networks:

  sonarqube-net:

volumes:

  sonar_conf:

  sonar_data:

  sonar_extensions:

  sonar_plugins:

  postgres_data:

    

 
