version: "3.7"
services:
  db:
    image: postgres:14.1-alpine
    environment:
        - POSTGRES_USER=sonar

        - POSTGRES_PASSWORD=sonar

        - POSTGRES_DB=sonar
    ports: 
        - '5432:5432'
    volumes:
        - postgres_data:/var/lib/postgresql/data
    restart: always


    

 
