version: '3.7'
services:
 backend:
  image: 149.102.138.184:8082/image-back/aoso:2.2.1
  container_name : back
  volumes:
      - ./:/var/www
  expose:
   - "5000"
  depends_on:
   - nginx_pro
  restart : always

 nginx_pro:
  image: 149.102.138.184:8082/image-nginx-backend/aoso:2.2.1
  container_name: nginx_Back
  volumes:
   - ./:/var/www
  ports:
   - "4001:80"
  restart : always
