- hosts: dev
  tasks:
      - name: Copy Docker-compose  
        copy:
            src: /var/Aosora/DevOps/Backend/docker-compose-back.yml
            dest: /var/Aosora/DevOps/Backend/
      - name: Deploy
        command: docker-compose -f /var/Aosora/DevOps/Backend/docker-compose-back.yml up -d
       